# Alpine Swiss Knife
#
# VERSION 1.0

FROM alpine:latest
MAINTAINER Gabriel Olcina <gabriel.olcina@gmail.com>

#Installing custom packages
RUN apk add --no-cache curl fish openssh

#Running entrypoint: fishshell
ENTRYPOINT ["fish"]
